class ClothRunner{
public static void main(String[] args)
{
	Cloth cloth=new Cloth();
	System.out.println(cloth.name);
	System.out.println(cloth.material);
	System.out.println(cloth.size);
	System.out.println(cloth.price);
	cloth.name="Sweator";
	cloth.material="wool";
	cloth.size=24;
	cloth.price=400;
	System.out.println("name of the cloth is:"+cloth.name);
	System.out.println("it is made by:"+cloth.material);
	System.out.println("cloth size is:"+cloth.size);
	System.out.println("cost of cloth:"+cloth.price);
	cloth.name="curtain";
	cloth.material="polyster";
	cloth.size=12;
	cloth.price=100;
	System.out.println("name of the cloth is:"+cloth.name);
	System.out.println("it is made by:"+cloth.material);
	System.out.println("cloth size is:"+cloth.size);
	System.out.println("cost of cloth:"+cloth.price);
	
	
Cloth cloth1=new Cloth();
System.out.println(cloth1.name);
System.out.println(cloth1.material);
System.out.println(cloth1.size);
System.out.println(cloth1.price);
cloth1.name="Shirt";
cloth1.material="Cotton";
cloth1.size=40;
cloth1.price=700;
System.out.println("name of the cloth is:"+cloth1.name);
System.out.println("it is made by:"+cloth1.material);
System.out.println("cloth size is:"+cloth1.size);
System.out.println("cost of cloth:"+cloth1.price);
cloth1.name="saree";
cloth1.material="Cotton";
cloth1.size=100;
cloth1.price=1000;
System.out.println("name of the cloth is:"+cloth1.name);
System.out.println("it is made by:"+cloth1.material);
System.out.println("cloth size is:"+cloth1.size);
System.out.println("cost of cloth:"+cloth1.price);


Cloth cloth2=new Cloth();
System.out.println(cloth2.name);
System.out.println(cloth2.material);
System.out.println(cloth2.size);
System.out.println(cloth2.price);
cloth2.name="Jacket";
cloth2.material="Leather";
cloth2.size=42;
cloth2.price=2500;
System.out.println("name of the cloth is:"+cloth2.name);
System.out.println("it is made by:"+cloth2.material);
System.out.println("cloth size is:"+cloth2.size);
System.out.println("cost of cloth:"+cloth2.price);
cloth2.name="Towel";
cloth2.material="cotton";
cloth2.size=15;
cloth2.price=100;
System.out.println("name of the cloth is:"+cloth2.name);
System.out.println("it is made by:"+cloth2.material);
System.out.println("cloth size is:"+cloth2.size);
System.out.println("cost of cloth:"+cloth2.price);

Cloth cloth3=new Cloth();
System.out.println(cloth3.name);
System.out.println(cloth3.material);
System.out.println(cloth3.size);
System.out.println(cloth3.price);
cloth3.name="Kurta";
cloth3.material="Silk";
cloth3.size=38;
cloth3.price=1200;
System.out.println("name of the cloth is:"+cloth3.name);
System.out.println("it is made by:"+cloth3.material);
System.out.println("cloth size is:"+cloth3.size);
System.out.println("cost of cloth:"+cloth3.price);
cloth3.name="Kurta set";
cloth3.material="Silk";
cloth3.size=38;
cloth3.price=1500;
System.out.println("name of the cloth is:"+cloth3.name);
System.out.println("it is made by:"+cloth3.material);
System.out.println("cloth size is:"+cloth3.size);
System.out.println("cost of cloth:"+cloth3.price);


Cloth cloth4=new Cloth();
System.out.println(cloth4.name);
System.out.println(cloth4.material);
System.out.println(cloth4.size);
System.out.println(cloth4.price);
cloth4.name="Tshirt";
cloth4.material="Polyester";
cloth4.size=36;
cloth4.price=500;
System.out.println("name of the cloth is:"+cloth4.name);
System.out.println("it is made by:"+cloth4.material);
System.out.println("cloth size is:"+cloth4.size);
System.out.println("cost of cloth:"+cloth4.price);

System.out.println("============================================================");

Stove stove4=new Stove();
System.out.println(stove4.name);
System.out.println(stove4.brand);
System.out.println(stove4.burners);
System.out.println(stove4.price);
stove4.name="HeatPro";
stove4.brand="Pigeon";
stove4.burners=1;
stove4.price=2500;
System.out.println("Stove name is:"+stove4.name);
System.out.println("Brand is:"+stove4.brand);
System.out.println("Number of burners:"+stove4.burners);
System.out.println("Price:"+stove4.price);
stove4.name="double stove";
stove4.brand="Pigeon";
stove4.burners=2;
stove4.price=6500;
System.out.println("Stove name is:"+stove4.name);
System.out.println("Brand is:"+stove4.brand);
System.out.println("Number of burners:"+stove4.burners);
System.out.println("Price:"+stove4.price);

Stove stove3=new Stove();
System.out.println(stove3.name);
System.out.println(stove3.brand);
System.out.println(stove3.burners);
System.out.println(stove3.price);
stove3.name="FlameStar";
stove3.brand="Sunflame";
stove3.burners=4;
stove3.price=6000;
System.out.println("Stove name is:"+stove3.name);
System.out.println("Brand is:"+stove3.brand);
System.out.println("Number of burners:"+stove3.burners);
System.out.println("Price:"+stove3.price);
stove3.name="FlameStar";
stove3.brand="butterfly";
stove3.burners=4;
stove3.price=6000;
System.out.println("Stove name is:"+stove3.name);
System.out.println("Brand is:"+stove3.brand);
System.out.println("Number of burners:"+stove3.burners);
System.out.println("Price:"+stove3.price);

Stove stove2=new Stove();
System.out.println(stove2.name);
System.out.println(stove2.brand);
System.out.println(stove2.burners);
System.out.println(stove2.price);
stove2.name="CookMaster";
stove2.brand="Butterfly";
stove2.burners=2;
stove2.price=3200;
System.out.println("Stove name is:"+stove2.name);
System.out.println("Brand is:"+stove2.brand);
System.out.println("Number of burners:"+stove2.burners);
System.out.println("Price:"+stove2.price);
stove2.name="pellet stove";
stove2.brand="Butterfly";
stove2.burners=4;
stove2.price=3500;
System.out.println("Stove name is:"+stove2.name);
System.out.println("Brand is:"+stove2.brand);
System.out.println("Number of burners:"+stove2.burners);
System.out.println("Price:"+stove2.price);

Stove stove1=new Stove();
System.out.println(stove1.name);
System.out.println(stove1.brand);
System.out.println(stove1.burners);
System.out.println(stove1.price);
stove1.name="KitchenPro";
stove1.brand="Prestige";
stove1.burners=3;
stove1.price=4500;
System.out.println("Stove name is:"+stove1.name);
System.out.println("Brand is:"+stove1.brand);
System.out.println("Number of burners:"+stove1.burners);
System.out.println("Price:"+stove1.price);
stove1.name="char coal stove";
stove1.brand="Prestige";
stove1.burners=3;
stove1.price=4000;
System.out.println("Stove name is:"+stove1.name);
System.out.println("Brand is:"+stove1.brand);
System.out.println("Number of burners:"+stove1.burners);
System.out.println("Price:"+stove1.price);

Stove stove5=new Stove();
System.out.println(stove5.price);
System.out.println(stove5.burners);
System.out.println(stove5.brand);
System.out.println(stove5.name);
stove5.price=5200;
stove5.burners=3;
stove5.brand="Havells";
stove5.name="FlamePlus";
System.out.println("Price:"+stove5.price);
System.out.println("Burners:"+stove5.burners);
System.out.println("Brand:"+stove5.brand);
System.out.println("Name:"+stove5.name);


System.out.println("============================================================");

Bridge bridge1=new Bridge();
System.out.println(bridge1.name);
System.out.println(bridge1.location);
System.out.println(bridge1.length);
System.out.println(bridge1.lanes);
bridge1.name="Golden Bridge";
bridge1.location="City Center";
bridge1.length=1200.5;
bridge1.lanes=4;
System.out.println("Bridge name:"+bridge1.name);
System.out.println("Location:"+bridge1.location);
System.out.println("Length:"+bridge1.length+" meters");
System.out.println("Lanes:"+bridge1.lanes);
bridge1.name="Rabindra setu ";
bridge1.location="west bengal ";
bridge1.length=2200.5;
bridge1.lanes=4;
System.out.println("Bridge name:"+bridge1.name);
System.out.println("Location:"+bridge1.location);
System.out.println("Length:"+bridge1.length+" meters");
System.out.println("Lanes:"+bridge1.lanes);

Bridge bridge2=new Bridge();
System.out.println(bridge2.name);
System.out.println(bridge2.location);
System.out.println(bridge2.length);
System.out.println(bridge2.lanes);
bridge2.name="RiverLink";
bridge2.location="North Zone";
bridge2.length=980.3;
bridge2.lanes=2;
System.out.println("Bridge name:"+bridge2.name);
System.out.println("Location:"+bridge2.location);
System.out.println("Length:"+bridge2.length+" meters");
System.out.println("Lanes:"+bridge2.lanes);
bridge2.name="Atal setu";
bridge2.location="mumbai ";
bridge2.length=980.3;
bridge2.lanes=2;
System.out.println("Bridge name:"+bridge2.name);
System.out.println("Location:"+bridge2.location);
System.out.println("Length:"+bridge2.length+" meters");
System.out.println("Lanes:"+bridge2.lanes);

Bridge bridge3=new Bridge();
System.out.println(bridge3.name);
System.out.println(bridge3.location);
System.out.println(bridge3.length);
System.out.println(bridge3.lanes);
bridge3.name="SkyPass";
bridge3.location="Highway";
bridge3.length=1500.0;
bridge3.lanes=6;
System.out.println("Bridge name:"+bridge3.name);
System.out.println("Location:"+bridge3.location);
System.out.println("Length:"+bridge3.length+" meters");
System.out.println("Lanes:"+bridge3.lanes);
bridge3.name="Howrag bridge";
bridge3.location="kolkata";
bridge3.length=1500.20;
bridge3.lanes=4;
System.out.println("Bridge name:"+bridge3.name);
System.out.println("Location:"+bridge3.location);
System.out.println("Length:"+bridge3.length+" meters");
System.out.println("Lanes:"+bridge3.lanes);

Bridge bridge4=new Bridge();
System.out.println(bridge4.name);
System.out.println(bridge4.location);
System.out.println(bridge4.length);
System.out.println(bridge4.lanes);
bridge4.name="LakeView";
bridge4.location="South City";
bridge4.length=720.8;
bridge4.lanes=3;
System.out.println("Bridge name:"+bridge4.name);
System.out.println("Location:"+bridge4.location);
System.out.println("Length:"+bridge4.length+" meters");
System.out.println("Lanes:"+bridge4.lanes);
bridge4.name="Tower bridge";
bridge4.location=" london";
bridge4.length=720.8;
bridge4.lanes=5;
System.out.println("Bridge name:"+bridge4.name);
System.out.println("Location:"+bridge4.location);
System.out.println("Length:"+bridge4.length+" meters");
System.out.println("Lanes:"+bridge4.lanes);

Bridge bridge5=new Bridge();
System.out.println(bridge5.name);
System.out.println(bridge5.location);
System.out.println(bridge5.length);
System.out.println(bridge5.lanes);
bridge5.name="MetroLink";
bridge5.location="Downtown";
bridge5.length=1100.4;
bridge5.lanes=5;
System.out.println("Bridge name:"+bridge5.name);
System.out.println("Location:"+bridge5.location);
System.out.println("Length:"+bridge5.length+" meters");
System.out.println("Lanes:"+bridge5.lanes);


System.out.println("============================================================");

Engine engine1=new Engine();
System.out.println(engine1.type);
System.out.println(engine1.horsepower);
System.out.println(engine1.capacity);
System.out.println(engine1.isRunning);
engine1.type="Petrol";
engine1.horsepower=120;
engine1.capacity=1.5;
engine1.isRunning=true;
System.out.println("Engine type:"+engine1.type);
System.out.println("Horsepower:"+engine1.horsepower);
System.out.println("Capacity:"+engine1.capacity+"L");
System.out.println("Running:"+engine1.isRunning);
engine1.type="two stroke";
engine1.horsepower=150;
engine1.capacity=2.0;
engine1.isRunning=true;
System.out.println("Engine type:"+engine1.type);
System.out.println("Horsepower:"+engine1.horsepower);
System.out.println("Capacity:"+engine1.capacity+"L");
System.out.println("Running:"+engine1.isRunning);


Engine engine2=new Engine();
System.out.println(engine2.type);
System.out.println(engine2.horsepower);
System.out.println(engine2.capacity);
System.out.println(engine2.isRunning);
engine2.type="Diesel";
engine2.horsepower=150;
engine2.capacity=2.0;
engine2.isRunning=false;
System.out.println("Engine type:"+engine2.type);
System.out.println("Horsepower:"+engine2.horsepower);
System.out.println("Capacity:"+engine2.capacity+"L");
System.out.println("Running:"+engine2.isRunning);
engine2.type="Flat engine";
engine2.horsepower=1000;
engine2.capacity=2.0;
engine2.isRunning=true;
System.out.println("Engine type:"+engine2.type);
System.out.println("Horsepower:"+engine2.horsepower);
System.out.println("Capacity:"+engine2.capacity+"L");
System.out.println("Running:"+engine2.isRunning);


Engine engine3=new Engine();
System.out.println(engine3.type);
System.out.println(engine3.horsepower);
System.out.println(engine3.capacity);
System.out.println(engine3.isRunning);
engine3.type="Electric";
engine3.horsepower=200;
engine3.capacity=0.0;
engine3.isRunning=true;
System.out.println("Engine type:"+engine3.type);
System.out.println("Horsepower:"+engine3.horsepower);
System.out.println("Capacity:"+engine3.capacity+"L");
System.out.println("Running:"+engine3.isRunning);
engine3.type="fuel";
engine3.horsepower=100;
engine3.capacity=2.0;
engine3.isRunning=true;
System.out.println("Engine type:"+engine3.type);
System.out.println("Horsepower:"+engine3.horsepower);
System.out.println("Capacity:"+engine3.capacity+"L");
System.out.println("Running:"+engine3.isRunning);


Engine engine4=new Engine();
System.out.println(engine4.type);
System.out.println(engine4.horsepower);
System.out.println(engine4.capacity);
System.out.println(engine4.isRunning);
engine4.type="Hybrid";
engine4.horsepower=180;
engine4.capacity=1.8;
engine4.isRunning=false;
System.out.println("Engine type:"+engine4.type);
System.out.println("Horsepower:"+engine4.horsepower);
System.out.println("Capacity:"+engine4.capacity+"L");
System.out.println("Running:"+engine4.isRunning);
engine4.type="petrol";
engine4.horsepower=280;
engine4.capacity=1.8;
engine4.isRunning=true;
System.out.println("Engine type:"+engine4.type);
System.out.println("Horsepower:"+engine4.horsepower);
System.out.println("Capacity:"+engine4.capacity+"L");
System.out.println("Running:"+engine4.isRunning);

Engine engine5=new Engine();
System.out.println(engine5.type);
System.out.println(engine5.horsepower);
System.out.println(engine5.capacity);
System.out.println(engine5.isRunning);
engine5.type="Turbo";
engine5.horsepower=220;
engine5.capacity=2.5;
engine5.isRunning=true;
System.out.println("Engine type:"+engine5.type);
System.out.println("Horsepower:"+engine5.horsepower);
System.out.println("Capacity:"+engine5.capacity+"L");
System.out.println("Running:"+engine5.isRunning);
engine5.type="FourStrokeEngine";
engine5.horsepower=220;
engine5.capacity=6.5;
engine5.isRunning=false;
System.out.println("Engine type:"+engine5.type);
System.out.println("Horsepower:"+engine5.horsepower);
System.out.println("Capacity:"+engine5.capacity+"L");
System.out.println("Running:"+engine5.isRunning);
}
}