class DolphinRunner{
	public static void main(String... values)
	{
		Dolphin dolphin=new Dolphin();
		dolphin.walk();
		dolphin.details();
		dolphin.swim();
		dolphin.swimming();
		dolphin.display();
		dolphin.getDetails();
		dolphin.emitWhistle();
		dolphin.forage();
		dolphin.flip();
		dolphin.getWeight();
		dolphin.getAge();
		dolphin.jumpOnScale();
		Dolphin.breathing();
		Dolphin.eat();
		Dolphin.energyLevel();
		
		Dolphin dolphin1=new Dolphin();
		dolphin1.walk();
		dolphin1.details();
		dolphin1.swim();
		dolphin1.swimming();
		dolphin1.display();
		dolphin1.getDetails();
		dolphin1.emitWhistle();
		dolphin1.forage();
		dolphin1.flip();
		dolphin1.getWeight();
		dolphin1.getAge();
		dolphin.jumpOnScale();
		Dolphin.breathing();
		Dolphin.eat();
		Dolphin.energyLevel();
		
		
		System.out.println("===================================================================");
		
		Bridge bridge=new Bridge();
		bridge.travel();
		bridge.openBridge();
		bridge.closedBridge();
		bridge.name();
		bridge.location();
		bridge.setlength();
		bridge.increaseCapacity();
		bridge.decreaseCapacity();
		bridge.safety();
		bridge.traffic();
		bridge.restrictTraffic();
		bridge.performanceMeasurement();
		bridge.display();
		Bridge.displayDetails();
		Bridge.calculateArea();
		Bridge.getWidth();
		Bridge.bridgeName();
		Bridge.Open();
		
		Bridge bridge1=new Bridge();
		bridge1.travel();
		bridge1.openBridge();
		bridge1.closedBridge();
		bridge1.name();
		bridge1.location();
		bridge1.setlength();
		bridge1.increaseCapacity();
		bridge1.decreaseCapacity();
		bridge1.safety();
		bridge1.traffic();
		bridge1.restrictTraffic();
		bridge1.performanceMeasurement();
		bridge1.display();
		bridge1.displayDetails();
		bridge1.calculateArea();
		bridge1.getWidth();
		bridge1.bridgeName();
		bridge1.Open();
		
		System.out.println("===============================================");
		
		Mountain mountain=new Mountain();
		mountain.climb();
		mountain.displayDetails();
		mountain.displayHeight();
		mountain.displayName();
		mountain.checkWhether();
		mountain.showWildLife();
		mountain.trekking();
		mountain.starttrekking();
		mountain.endTrekking();
		mountain.bestSeason();
		mountain.printDetail();
		mountain.slope();
		mountain.showSunsetView();
		mountain.displayHistory();
		mountain.showSunriseView();
		Mountain.difficultyLevel();
		Mountain.measureTemperature();
		Mountain.descend();
		Mountain.calculateSlopes();
		Mountain.showFampousSpot();
		
		Mountain mountain1=new Mountain();
		mountain1.climb();
		mountain1.displayDetails();
		mountain1.displayHeight();
		mountain1.displayName();
		mountain1.checkWhether();
		mountain1.showWildLife();
		mountain1.trekking();
		mountain1.starttrekking();
		mountain1.endTrekking();
		mountain1.bestSeason();
		mountain1.printDetail();
		mountain1.slope();
		mountain1.showSunsetView();
		mountain1.displayHistory();
		mountain1.showSunriseView();
		Mountain.difficultyLevel();
		Mountain.measureTemperature();
		Mountain.descend();
		Mountain.calculateSlopes();
		Mountain.showFampousSpot();
		
		System.out.println("===========================================================");
		
		Hamper hamper = new Hamper();
         hamper.openHamper();
         hamper.closeHamper();
         hamper.addItem();
         hamper.removeItem();
         hamper.displayItems();
         hamper.checkWeight();
         hamper.cleanHamper();
         hamper.arrangeItems();
         hamper.sealHamper();
         hamper.unsealHamper();
         hamper.giftWrap();
         hamper.printLabel();
         hamper.checkAvailability();
         hamper.updatePrice();
         hamper.returnHamper();
		 Hamper.checkQuality();
         Hamper.packHamper();
         Hamper.deliverHamper();
         Hamper.priceDetails();
         Hamper.offerDetails();

         Hamper hamper1 = new Hamper();
		 hamper1.openHamper();
         hamper1.closeHamper();
         hamper1.addItem();
         hamper1.removeItem();
         hamper1.displayItems();
         hamper1.checkWeight();
         hamper1.cleanHamper();
         hamper1.arrangeItems();
         hamper1.sealHamper();
         hamper1.unsealHamper();
         hamper1.giftWrap();
         hamper1.printLabel();
         hamper1.checkAvailability();
         hamper1.updatePrice();
         hamper1.returnHamper();
         Hamper.checkQuality();
         Hamper.packHamper();
         Hamper.deliverHamper();
         Hamper.priceDetails();
         Hamper.offerDetails();
		
		System.out.println("===========================================================");
		
		Penguin penguin = new Penguin();
		penguin.swim();
		penguin.walk();
        penguin.eat();
        penguin.sleep();
        penguin.dive();
        penguin.slideOnIce();
        penguin.huntFish();
        penguin.buildNest();
        penguin.protectEgg();
        penguin.feedChick();
        penguin.flapWings();
        penguin.makeSound();
        penguin.shakeBody();
        penguin.migrate();
        penguin.rest();
        Penguin.speciesInfo();
        Penguin.habitat();
        Penguin.averageHeight();
        Penguin.averageWeight();
        Penguin.conservationStatus();

        Penguin penguin1 = new Penguin();
penguin1.swim();
penguin1.walk();
penguin1.eat();
penguin1.sleep();
penguin1.dive();
penguin1.slideOnIce();
penguin1.huntFish();
penguin1.buildNest();
penguin1.protectEgg();
penguin1.feedChick();
penguin1.flapWings();
penguin1.makeSound();
penguin1.shakeBody();
penguin1.migrate();
penguin1.rest();
Penguin.speciesInfo();
Penguin.habitat();
Penguin.averageHeight();
Penguin.averageWeight();
Penguin.conservationStatus();
	}
}